### ISSUE TITLE
Mapeo de Joystick

### ISSUE THREAD

**Issue by maxiyommi** [orsai-tech/orsai-insta360#1]
La cámara insta360-link tiene un gimbal que posee tres grados de libertad (pan, tilt, roll)
![image](https://github.com/orsai-tech/orsai-insta360/assets/24780670/83b2739e-610d-4da6-ac65-169b68ab0228)

## Task
* Mapear los movimientos de pan y tilt de la cámara al movimiento del joystick de la webapp.
  * Tener en cuenta los límites de movimiento. Para evitar forzar los motores.
* Agregar un factor de sensibilidad y poderlo modificar desde la webapp.
* Verificar funcionamiento desde un cliente externo (PC/Mobile).

## Test
* Crear una brach para la nueva feature.
* Subirla al repo remoto (nueva rama).
* Descarga en RPi y realizar las pruebas.
* Agregar nueva característica al [README.ml](https://github.com/orsai-tech/orsai-insta360/blob/develop/app/README.md#-caracter%C3%ADsticas-del-release).

**Comment by GonzaRJ** [comment]
Al commit [d67c70d](https://github.com/orsai-tech/orsai-insta360/commit/d67c70d783818fc0d4c622cd454e8469e1c6738c) el issue quedo en:
- Un control remoto estable pero no demasiado óptimo con el principal problema de que las instrucciones desde el joystick no son procesadas a tiempo, produciendo que queden en cola y la cámara se siga moviendo una vez finalizado el movimiento del joystick.
- Una posible solución es limitando la cantidad de instrucciones que se envían desde la web App.

**Comment by GonzaRJ** [comment]
Se cierra el issue para esta versión con los errores detallados en el comentario anterior
