### ISSUE TITLE
Servicios de inicio en la RPi

### ISSUE THREAD

**Issue by maxiyommi** [orsai-tech/orsai-insta360#7]
Para garantizar la automatización del proyecto es necesario iniciar una lista de servicios con el encendido de la RPi.

## Task
Los servicios a definir son:
* [app.py](https://github.com/orsai-tech/orsai-insta360/blob/feature/MapeoDeJoystick/app/app.py)
*  [Boton de apagado de RPi](https://github.com/orsai-tech/orsai-insta360/issues/5).
* Servicio de Streaming por RSTP.

## Ejemplo

``` bash
# Configurar servicio para que el procesamiento inicie al prender la RPi.
sudo echo -e '[Unit]\nDescription=Servicio que ejecuta el archivo app de orsai-insta360\nRequires=multi-user.target\nAfter=multi-user.target\n\n[Service]\nType=idle\nExecStart=/usr/bin/python3 /home/app/app.py\n\n[Install]\nRequiredBy=multi-user.target' > orsai-insta360.service && sudo mv orsai-insta360.service /lib/systemd/system/orsai-insta360.service
sudo systemctl daemon-reload
sudo systemctl enable orsai-insta360.service
```
>  Agregar la definicion de estos servicios en el archivo [initial_setup.sh](https://github.com/orsai-tech/orsai-insta360/issues/3)

**Comment by GonzaRJ** [comment]
Se configuraron 2 servicios llamados inicio_app.service, el cual ejecuta el app.py e instancia la webapp, y otro llamdo inicio_kisko.service, el cual corre el archivo kiosk.sh en el cual se corren los comando necesarios para el modo kisko y los comando ffplay que activa la camara y el xdotool que la vuelve pantalla completa.
Sin emabrgo, este último servicio no logra hacer que se muestre en la pantalla la camara, la misma se pone en verde, por lo que el comando se ejecuta, pero no se abre la ventana. Cuando el .sh se ejecuta manuamente funciona de manera correcta. 
Por otro lado, se debrá editar el kisk.sh ya que el comando ffplay frena la ejecución de las lineas que se encuantran debajo de ella.

**Comment by GonzaRJ** [comment]
El [commit "9 Mejoras en el funcionamiento"](https://github.com/orsai-tech/orsai-insta360/commit/ae71ba3e975b9bcd7224d764a4fc4c699d01b989) hace referencia a este issue y fue nomencaldo erroneamente.

Se corrigió el error en el que el init_max generaba flashes en la pantalla haciendo que se interrumpa su ejecucuión luego de 3 iteraciones. Por otro lado, se cambió la resolución de hd720@30 fps a hd1080@24. Se intentó colocar en 4k pero no se freezeaba la imagen en el primer frame. 
Este cambio hace que la camara ya se habra en fullscreen, pero igualmente se deja el inicio_max por si se utliliza alguna camara con otro formato (inicio_max usa de referencia 100% del windowsize). Ademas de que puede ser util en futuras implementaciones de mas camaras.
A su vez, se agrega el archivo 'xterm_max.sh' que falto en el commmit anterior.
Por último, el inconveniente del led rojo sigue por lo que se debe prender la misma unos 20 minutos antes de usarse correctamente.
