### ISSUE TITLE
Agregar un indicador de la posición absoluta

### ISSUE THREAD

**Issue by maxiyommi** [orsai-tech/orsai-insta360#8]
Para poder almacenarlas en una futura característica de la webapp y crear escenas.

## Task
* Agregar un display que indique el valor de **pan absoluto** que se ubica actualmente en la cámara.
* Agregar un display que indique el valor de **tilt absoluto** que se ubica actualmente en la cámara.

> Estos elementos deberia estar ubicados abajo del joystick.

**Comment by GonzaRJ** [comment]
El indicador de posición absoluta funciona correctamente, a excepción de cuando se carga una escena debido a que el mismo no se actualiza hasta utilizar el joystick nuevamente
