### ISSUE TITLE
Agregar botón para almacenar escenas

### ISSUE THREAD

**Issue by maxiyommi** [orsai-tech/orsai-insta360#9]
En una situación de streaming es útil contar con la capacidad de almacenar posiciones absolutas, para mover rápidamente la cámara a una posición prefijada.

## Task
* A partir del issue #8, agregar un botón que permita almacenar dicha posición absoluta de pan y tilt. 
* Agregar un elemento display al lado del botón para indicar las posiciones de pan y tilt almacenada.

**Comment by GonzaRJ** [comment]
Se colocar 6 botones (3 para guardar y 3 para cargar) para el uso de 3 escenas, pero puede extenderse a cuantas se quiera con modificar solo 2 lineas del codigo de la app
